### ISSUE TITLE
Password lists for different languages

### ISSUE THREAD

**Issue by ratok-mk** [Aaron-P/KeeDiceware#1]
Hello I would like to have some additional dice ware word lists or configurable wordlists for the most common languages:
German
English - already included
French
Italian
Spanish
Japanese
Chinese
Russian

They can be obtained here:
https://theworld.com/~reinhold/diceware.html#Diceware%20in%20Other%20Languages|outline

**Comment by Aaron-P** [comment]
I looked at a bunch of the sites listed on the link you gave and I'm concerned about the licensing on a bunch of them.  A bunch are GPL, which I'm not sure I want to hard-include in my MIT licensed project and some are listed as being CC-BY but I couldn't find any licensing info on the actual sites. Right now I think the better option will be to add some mechanism for loading custom word lists so the user's can just import one. I'm going to have to think about the UI for that though.

**Comment by ratok-mk** [comment]
> 
> 
> I looked at a bunch of the sites listed on the link you gave and I'm concerned about the licensing on a bunch of them. A bunch are GPL, which I'm not sure I want to hard-include in my MIT licensed project and some are listed as being CC-BY but I couldn't find any licensing info on the actual sites. Right now I think the better option will be to add some mechanism for loading custom word lists so the user's can just import one. I'm going to have to think about the UI for that though.

**Comment by ratok-mk** [comment]
The custom loading of words sounds like a good idea to overcome the licensing issue.

**Comment by Aaron-P** [comment]
I have added simple support for custom word lists. You can read the README.md file to see how they are used.

**Comment by ratok-mk** [comment]
I have tested it and it looks great.
